expense/urls.py
from django.conf.urls import url

from . import views

app_name = 'expense'
urlpatterns = [
    # ex: /company/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /company/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /company/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /company/5/select/
    url(r'^(?P<company_id>[0-9]+)/select/$', views.select, name='select'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^company/', include('expense.urls')),
    # url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls),
]

expense/models.py
from django.db import models


class Company(models.Model):
    company_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.company_name

class Department(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    department_name = models.CharField(max_length=200)
    selection = models.IntegerField(default=0)

    def __str__(self):
        return self.department_name

expense/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Company, Department


class IndexView(generic.ListView):
    template_name = 'expense/index.html'
    context_object_name = 'company_list'

    def get_queryset(self):
        """Return the last five published Companys."""
        return Company.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Company
    template_name = 'expense/detail.html'


class ResultsView(generic.DetailView):
    model = Company
    template_name = 'expense/results.html'

def select(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    try:
        selected_department = company.department_set.get(pk=request.POST['department'])
    except (KeyError, Department.DoesNotExist):
        # Redisplay the company voting form.
        return render(request, 'expense/detail.html', {
            'company': company,
            'error_message': "You didn't select a department.",
        })
    else:
        selected_department.selection += 1
        selected_department.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('expense:results', args=(company.id,)))

expense/templates/expense/detail.html
<h1>{{ company.company_name }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'expense:select' company.id %}" method="post">
{% csrf_token %}
{% for department in company.department_set.all %}
    <input type="radio" name="department" id="department{{ forloop.counter }}" value="{{ department.id }}" />
    <label for="department{{ forloop.counter }}">{{ department.department_name }}</label><br />
{% endfor %}
<input type="submit" value="Select" />
</form>

expense/templates/expense/index.html
{% if company_list %}
    <ul>
    {% for company in company_list %}
        <li><a href="{% url 'expense:detail' company.id %}">{{ company.company_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No company available.</p>
{% endif %}

expense/templates/expense/results.html
<h1>{{ company.company_name }}</h1>

<ul>
{% for department in company.department_set.all %}
    <li>{{ department.department_name }} -- {{ department.selection }} selection{{ department.selections|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'expense:detail' company.id %}">Select again?</a>